### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dmnc-net** [dmnc-net/repository.dmnc#1]
- [ ] non-static addon/repo #2
- [ ] xml fine tunning (multilang, graphics, news, ...)
- [ ] finally move zip to Releases and upload addon(s).xml source to Code
